require "utils"
require "keymappings"
require "settings"
require "plugins"
require "colorscheme"
-- LSP
-- require "lsp"
-- require "lsp.lua-language-server"
-- require "lsp.pyright"
-- require "lsp.clangd"
-- require "config.treesitter"
